# Generated by Django 6.1.1 on 2026-09-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.business'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document'),
        ),
        migrations.AddField(
            model_name='vectorref',
            name='chunk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_ref', to='documents.chunk'),
        ),
    ]
