# Generated by Django 5.1.10 on 2026-09-17 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_proposal'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompttemplate',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='querylog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='users.business'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['business', '-created_at'], name='rag_querylo_busines_9a1c3c_idx'),
        ),
    ]
